name: Release v5.x

on:
  push:
    tags: ['v5.[0-9]+.[0-9]+']

jobs:
  npm:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: lts/iron # 20
          registry-url: https://registry.npmjs.org
          always-auth: true
      - run: npm publish --provenance --tag previous
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  github:
    needs:
      - npm
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: lts/iron # 20
          cache: 'npm'
      - run: node .release-notes.cjs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
